imports:
  - { resource: 'services_config.yml' }

parameters:
  module_settings:
    configuration:
      'REVERS_IO_API_PUBLIC_KEY' : ''
      'REVERS_IO_API_SECRET_KEY' : ''
      'REVERS_IO_TEST_MODE_SETTING' : 1
      'REVERS_IO_ORDER_STATUS' : ''
      'REVERS_IO_ENABLE_LOGGING_SETTING' : 0
      'REVERS_IO_STORE_LOGS' : 0
      'REVERS_IO_DEFAULT_DIMENSIONS' : 0
      'REVERS_IO_PRODUCT_INIT_EXPORT' : 1
      'REVERS_IO_BRAND_INIT_EXPORT' : 1

    hooks:
      - 'actionAdminOrdersListingFieldsModifier'
      - 'displayAdminOrder'
      - 'displayOrderDetail'
      - 'actionObjectProductUpdateAfter'
      - 'actionObjectProductDeleteAfter'
      - 'actionObjectProductAddAfter'
      - 'actionAdminControllerSetMedia'
      - 'actionFrontControllerSetMedia'
      - 'actionOrderStatusUpdate'
      - 'moduleRoutes'
